repos:
  - repo: local
    hooks:
      - id: isort
        exclude: (poetry.lock|pyproject.toml|migrations)
        name: isort
        entry: isort
        language: system
        types: [ python ]


      - id: black
        exclude: (poetry.lock|pyproject.toml|migrations)
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=100, --target-version=py37]


      -   id: flake8
          exclude: (poetry.lock|pyproject.toml|migrations)
          name: flake8
          entry: flake8
          language: system
          types: [python]
          args: ["--max-line-length=110"]

