version: "3.9"
networks:
  default:
    external:
      name: credit-microservice_default

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - /a-geld/data/db_user:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=microservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_PORT=5433
    ports:
      - "5433:5432"
  web:
    image: $AND_DOCKER_REGISTRY_NAME/$PROJECT-$APP1:$CI_COMMIT_BRANCH
    container_name: ${APP1}
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=microservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
