# Generated by Django 4.1.5 on 2023-02-20 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("abf5098f-262a-4e85-b907-ac1e4cd539fc"), unique=True
            ),
        ),
    ]
