# Generated by Django 4.1.5 on 2023-02-21 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0003_alter_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("942e9e46-ec77-4543-9703-3299ccfbfbce"), unique=True
            ),
        ),
    ]
