# Generated by Django 4.1.5 on 2023-02-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0002_alter_client_uuid"),
        ("user_service", "0005_alter_client_uuid"),
    ]

    operations = []
