# Generated by Django 4.1.5 on 2023-02-27 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0006_alter_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("a9b3f732-e888-43f5-868d-676f0dae1f77"), unique=True
            ),
        ),
    ]
