# Generated by Django 4.1.5 on 2023-02-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0007_alter_client_uuid_pincode"),
        ("user_service", "0008_alter_client_uuid"),
    ]

    operations = []
